const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Create Schema and Model

const MassageformSchema = new Schema({
    id: Number,
    type: String,
    fullname: String,
    phone: String,
    address: String,
    citystate: String,
    email: String,
    datebirth: Date,
    occupation: String,
    emergencyname: String,
    emergencyphone: String,
    havepro: Boolean,
    howofter: String,
    difficulty: Boolean,
    qt_two_explain: String,
    allergies: Boolean,
    qt_three_explain: String,
    sensitive: Boolean,
    contactlenses: Boolean,
    dentures: Boolean,
    hearing: Boolean,
    workstation: Boolean,
    qt_six_explain: String,
    repetitive: Boolean,
    qt_seven_explain: String,
    experience: Boolean,
    muscle: Boolean,
    anxiety: Boolean,
    insomnia: Boolean,
    irritability: Boolean,
    other: String,
    particular: Boolean,
    qt_nigth_explain: String,
    goals: Boolean,
    qt_ten_explain: String,
    arms: Boolean,
    legs: Boolean,
    feet: Boolean,
    shoulder: Boolean,
    hip: Boolean,
    uperback: Boolean,
    lowerback: Boolean,
    calves: Boolean,
    medical: Boolean,
    qt_eleven_explain: String,
    chiropractor: Boolean,
    qt_twele_explain: String,
    medication: Boolean,
    qt_trece_explain: String,
    cont_contagious: Boolean,
    cont_sores: Boolean,
    cont_bruising: Boolean,
    accident: Boolean,
    fracture: Boolean,
    surgery: Boolean,
    artificial: Boolean,
    sprains: Boolean,
    fever: Boolean,
    swollen: Boolean,
    sensitivity: Boolean,
    heart: Boolean,
    blood: Boolean,
    circulatory: Boolean,
    varicose: Boolean,
    rheumatoid: Boolean,
    atherosclerosis: Boolean,
    phlebitis: Boolean,
    thrombosis: Boolean,
    osteoporosis: Boolean,
    epilepsy: Boolean,
    migraines: Boolean,
    cancer: Boolean,
    diabetes: Boolean,
    sensation: Boolean,
    neck: Boolean,
    fibromyalgia: Boolean,
    tmj: Boolean,
    carpal: Boolean,
    tennis: Boolean,
    pregnancy: Boolean,
    manymonth: String,
    conditionexplain: String,
    anything:String ,
    signature: String,
    clientid: Number,
    datecreated: Date,
    dateinitial: String,
    minorfullname: String
});


const Massageform = mongoose.model('massageforms', MassageformSchema);

module.exports = Massageform;